spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.5.210.93:3306/online_market?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: Xjj1454941121
  config:
    activate:
      on-profile: prod
mybatis-plus:
  mapper-locations: classpath*:/mapper/**.xml
server:
  port: 8081
xjj:
  imgfilepath: "/home/ubuntu/imgs/"