spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/online_market?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  config:
    activate:
      on-profile: dev
  redis:
    database: 0
    host: 121.5.210.93
    port: 6379
    password:
    timeout: 1000
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 50
        max-wait: -1
mybatis-plus:
  mapper-locations: classpath*:/mapper/**.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
server:
  port: 8081
xjj:
  imgfilepath: "D:/图片/"
